{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-redis
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}